### ISSUE TITLE
Automated build on quay.io

### ISSUE THREAD

**Issue by LoicMahieu** [mhart/alpine-node#6]
Hi

I started a repository on quay.io [`quay.io/loicmahieu/alpine-node`](https://quay.io/repository/loicmahieu/alpine-node) for testing `git tag` to `docker tag` and it works pretty well so I thought that it can be useful to share the idea here.

So the idea behind image `quay.io/loicmahieu/alpine-node` is:
- **Automated build**: I suppose @mhart currently builds all images in his own and push it to Docker Hub.
- **Git tag for each version**: Better visibility in Github etc...
  Examples:

```
base-v3.3.0
v3.3.0
base-v4.0.0
v4.0.0
```

Tags without `base-` are full build.
- **One image regardless of iojs/node**: iojs and node version names are not conflicting together so we can have only one image.
- **Git tag become Docker tag**: Quay.io is the only repository hosting (that I know !?) that allows you to automatically make docker tag from git tag. You can filter it with a regex. Regex used here is: `(heads/master)|(tags/(base-)?v([0-9]+)\.([0-9]+)\.([0-9]+))`

At this time, the image `quay.io/loicmahieu/alpine-node` is build from my [fork](https://github.com/LoicMahieu/alpine-node). The only difference between my fork and @mhart is the git tags. I written a small script for automatically create tags from commit message: https://gist.github.com/LoicMahieu/db7e5f4916714d97fb67

Caveat of Quay.io:
- You can't push multiple tags are the same time... Really annoying but we can workaround in `git push origin [tag]` one tag at the time.

My idea behind this issue is only to open the discussion.
Thanks!

**Comment by mhart** [comment]
Cool! Thanks for opening a discussion on this. Some interesting ideas in here.

I like the `base-` tagging – I originally thought about doing this, but then it conflicted with the idea of just being able to do `FROM mhart/alpine-node-base` in your `Dockerfile` and always get the latest version. I guess it could be changed to `FROM mhart/alpine-node:base` and then ensure that tag is generated from the latest base too. Hmmm, will think about this.

(also, now that Node and io.js have caught up, you're right that there aren't any conflicting versions, but when io.js originally forked, it wasn't clear what Node would do with their versioning – it was only later that they came to agreement on that, so I decided to err on the side of caution)

In terms of using quay.io in general, it looks quite good! I kinda wish this sort of tag-matching functionality was just supported by the main Docker hub (maybe it has more support for these sorts of configurations since I last looked?)

Anyway, you've inspired me to look into consolidating all the images into just `alpine-node` and using tags off that – and maybe I'll add git tags too, in the hope that Docker hub will catch up to that functionality.

**Comment by mhart** [comment]
Closing this as I've added automated builds over at https://hub.docker.com/r/mhart/alpine-node-auto as per #33
