### ISSUE TITLE
Yarn without npm 

### ISSUE THREAD

**Issue by Globegitter** [mhart/alpine-node#89]
Love seeing the yarn support with the latest image. Would it be possible to also get a tag, e.g. yarn-8 to have an image with yarn but without npm?

**Comment by onetom** [comment]
I was wondering what would be the most minimal build environment for a modern nodejs app.

So I just asked myself the same question if it's possible to have only `yarn` but not `npm` in this image, but after some digging I'm not sure it's something I want anymore. These articles made me question how sound is Yarn itself:

* https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf
* https://medium.com/@boennemann/questions-i-wish-yarn-had-answered-on-day-1-ec0db7458107

Then I checked what's available on docker hub and I found [node-alpine-yarn](https://hub.docker.com/r/jfyne/node-alpine-yarn/~/dockerfile/) which installs the latest Yarn into `/usr/local/bin` BUT on top of the `node:alpine` image which [does include Yarn](https://github.com/nodejs/docker-node/blob/09e42c172ffd6f8631fb1cb7a0785fd890c0f11a/8.0/alpine/Dockerfile#L49-L67) under `/opt/yarn/bin`.

Does Yarn require `npm`? I mean the `/usr/local/lib/node_modules/npm/` folder in the `node:alpine` image?

Disclaimer: I'm not really working with Nodejs for ~3years now, just with Clojure. I'm just looking into Yarn because a vendor of ours would prefer to use it.

**Comment by wclr** [comment]
For now yarn just still have a few unresolved issues referri to packaging/publishing/globals. So it is useful to have npm at hand when you need such operations.

Though yarn fixed multiple issues in the latest releases (0.27).

@mhart do plan to update images for new yarn version?

**Comment by karimsa** [comment]
Perhaps I'm missing something here but is it not enough to have both yarn & npm in an alpine image and then utilize the multi-stage setup? Since a production app should not really need a package manager since the code should be in a frozen state + the purpose behind docker is to have furthermore stateless containers.

Side note (@onetom): with regards to your comment about yarn's soundness, the tool is still young and `npm`s stability is far greater since there is a bigger team behind it and it has been around for much longer.

**Comment by mhart** [comment]
Closing this – a bit too niche to support IMO
